/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as SSessionIdRouteImport } from './routes/s.$sessionId'
import { Route as SessionsCreateRouteImport } from './routes/sessions.create'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as SettingsSectionRouteImport } from './routes/settings.$section'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const SSessionIdRoute = SSessionIdRouteImport.update({
  id: '/s/$sessionId',
  path: '/s/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsCreateRoute = SessionsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => SessionsRoute,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSectionRoute = SettingsSectionRouteImport.update({
  id: '/settings/$section',
  path: '/settings/$section',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sessions': typeof SessionsRouteWithChildren
  '/s/$sessionId': typeof SSessionIdRoute
  '/sessions/create': typeof SessionsCreateRoute
  '/settings/$section': typeof SettingsSectionRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sessions': typeof SessionsRouteWithChildren
  '/s/$sessionId': typeof SSessionIdRoute
  '/sessions/create': typeof SessionsCreateRoute
  '/settings/$section': typeof SettingsSectionRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sessions': typeof SessionsRouteWithChildren
  '/s/$sessionId': typeof SSessionIdRoute
  '/sessions/create': typeof SessionsCreateRoute
  '/settings/$section': typeof SettingsSectionRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sessions'
    | '/s/$sessionId'
    | '/sessions/create'
    | '/settings/$section'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sessions'
    | '/s/$sessionId'
    | '/sessions/create'
    | '/settings/$section'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/sessions'
    | '/s/$sessionId'
    | '/sessions/create'
    | '/settings/$section'
    | '/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SessionsRoute: typeof SessionsRouteWithChildren
  SSessionIdRoute: typeof SSessionIdRoute
  SettingsSectionRoute: typeof SettingsSectionRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$sessionId': {
      id: '/s/$sessionId'
      path: '/s/$sessionId'
      fullPath: '/s/$sessionId'
      preLoaderRoute: typeof SSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/create': {
      id: '/sessions/create'
      path: '/create'
      fullPath: '/sessions/create'
      preLoaderRoute: typeof SessionsCreateRouteImport
      parentRoute: typeof SessionsRoute
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/$section': {
      id: '/settings/$section'
      path: '/settings/$section'
      fullPath: '/settings/$section'
      preLoaderRoute: typeof SettingsSectionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SessionsRouteChildren {
  SessionsCreateRoute: typeof SessionsCreateRoute
}

const SessionsRouteChildren: SessionsRouteChildren = {
  SessionsCreateRoute: SessionsCreateRoute,
}

const SessionsRouteWithChildren = SessionsRoute._addFileChildren(
  SessionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SessionsRoute: SessionsRouteWithChildren,
  SSessionIdRoute: SSessionIdRoute,
  SettingsSectionRoute: SettingsSectionRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
