// Writes codex-protocol.ts: the app-server types the Codex stand-in sends, generated by the Codex
// the image pins (`codex app-server generate-ts`), so typecheck holds the stand-in to that
// version's protocol. Run `npm run protocol:codex` after changing the pinned Codex.
import { execFileSync } from "node:child_process";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, normalize, relative } from "node:path";

const here = dirname(new URL(import.meta.url).pathname);
const version = /@openai\/codex@([\d.]+)/.exec(
  readFileSync(join(here, "../Dockerfile"), "utf8"),
)?.[1];
if (version === undefined) throw new Error("container/Dockerfile pins no @openai/codex version");

// What the stand-in replies and notifies; everything they refer to comes along.
const roots = [
  "InitializeResponse",
  "v2/ThreadStartResponse",
  "v2/ThreadResumeResponse",
  "v2/ThreadStartedNotification",
  "v2/ThreadStatusChangedNotification",
  "v2/TurnStartResponse",
  "v2/TurnSteerResponse",
  "v2/TurnInterruptResponse",
  "v2/TurnStartedNotification",
  "v2/TurnCompletedNotification",
  "v2/ItemStartedNotification",
  "v2/ItemCompletedNotification",
  "v2/AgentMessageDeltaNotification",
  "v2/CommandExecutionOutputDeltaNotification",
];

const out = mkdtempSync(join(tmpdir(), "codex-protocol-"));
try {
  execFileSync(
    "npx",
    ["-y", `@openai/codex@${version}`, "app-server", "generate-ts", "--out", out],
    { stdio: ["ignore", "ignore", "inherit"] },
  );
  const seen = new Map<string, string>();
  const visit = (file: string) => {
    if (seen.has(file)) return;
    const source = readFileSync(file, "utf8");
    seen.set(file, source);
    for (const [, path = ""] of source.matchAll(/from "(\.[^"]+)"/g))
      visit(normalize(join(dirname(file), `${path}.ts`)));
  };
  for (const root of roots) visit(join(out, `${root}.ts`));
  // One file: the imports go, as every type they named is in it. Names don't collide.
  const types = [...seen]
    .sort(([a], [b]) => relative(out, a).localeCompare(relative(out, b)))
    .map(([, source]) =>
      source
        .split("\n")
        .filter((line) => !line.startsWith("import type ") && !line.startsWith("//"))
        .join("\n")
        .trim(),
    );
  writeFileSync(
    join(here, "codex-protocol.ts"),
    `// Generated by codex-protocol.gen.ts from Codex ${version}. Don't edit.\n\n${types.join("\n\n")}\n`,
  );
} finally {
  rmSync(out, { recursive: true, force: true });
}
